### PR TITLE
http instead of https

### PR DESCRIPTION
**Pull request by dmn001**

### CODE REVIEW

**Comment by Phoenix1747** [comment]
Works fine with http instead of https! 👍

**Comment by theanidox** [comment]
Yep @Jackathan website works with HTTP instead of HTTPS. Merge.

**Comment by Restioson** [comment]
@Phoenix1747 did you merge this? Seems like it's still open?

**Comment by Phoenix1747** [comment]
@Restioson Yes, but I can only merge it with my fork right here: [Github fork](https://github.com/Phoenix1747/MarcLaidlaw-Epistle3)

**Pull request closed without merging**
